services:
    nginx:
       build:
           context: ./nginx
       ports:
           - "80:80"
           - "443:443"
           - "8000:8000"
       volumes:
         - ./www:/var/www
         - ./nginx/conf.d/:/etc/nginx/conf.d/